apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: re40wji4z-go
  janus-idp.io/tekton: re40wji4z-go
  backstage.io/kubernetes-id: re40wji4z-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: re40wji4z-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
