apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: re40wji4z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: re40wji4z-go 
  name: re40wji4z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: re40wji4z-go 
